# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import protobuf.whatsapp_pb2 as whatsapp__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in whatsapp_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WhatsAppServiceStub(object):
    """Service definition for WhatsApp session management
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartSession = channel.unary_stream(
                '/whatsapp.WhatsAppService/StartSession',
                request_serializer=whatsapp__pb2.StartSessionRequest.SerializeToString,
                response_deserializer=whatsapp__pb2.SessionResponse.FromString,
                _registered_method=True)
        self.CheckSessionStatus = channel.unary_unary(
                '/whatsapp.WhatsAppService/CheckSessionStatus',
                request_serializer=whatsapp__pb2.SessionStatusRequest.SerializeToString,
                response_deserializer=whatsapp__pb2.SessionStatusResponse.FromString,
                _registered_method=True)
        self.SendMessage = channel.unary_unary(
                '/whatsapp.WhatsAppService/SendMessage',
                request_serializer=whatsapp__pb2.SendMessageRequest.SerializeToString,
                response_deserializer=whatsapp__pb2.SendMessageResponse.FromString,
                _registered_method=True)


class WhatsAppServiceServicer(object):
    """Service definition for WhatsApp session management
    """

    def StartSession(self, request, context):
        """Start a new WhatsApp session and get QR code
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckSessionStatus(self, request, context):
        """Check session status by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """Send message and get status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WhatsAppServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartSession': grpc.unary_stream_rpc_method_handler(
                    servicer.StartSession,
                    request_deserializer=whatsapp__pb2.StartSessionRequest.FromString,
                    response_serializer=whatsapp__pb2.SessionResponse.SerializeToString,
            ),
            'CheckSessionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckSessionStatus,
                    request_deserializer=whatsapp__pb2.SessionStatusRequest.FromString,
                    response_serializer=whatsapp__pb2.SessionStatusResponse.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=whatsapp__pb2.SendMessageRequest.FromString,
                    response_serializer=whatsapp__pb2.SendMessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'whatsapp.WhatsAppService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('whatsapp.WhatsAppService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WhatsAppService(object):
    """Service definition for WhatsApp session management
    """

    @staticmethod
    def StartSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/whatsapp.WhatsAppService/StartSession',
            whatsapp__pb2.StartSessionRequest.SerializeToString,
            whatsapp__pb2.SessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckSessionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/whatsapp.WhatsAppService/CheckSessionStatus',
            whatsapp__pb2.SessionStatusRequest.SerializeToString,
            whatsapp__pb2.SessionStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/whatsapp.WhatsAppService/SendMessage',
            whatsapp__pb2.SendMessageRequest.SerializeToString,
            whatsapp__pb2.SendMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
