// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: whatsapp.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Empty request for starting a new session
type StartSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionRequest) Reset() {
	*x = StartSessionRequest{}
	mi := &file_whatsapp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionRequest) ProtoMessage() {}

func (x *StartSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whatsapp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionRequest.ProtoReflect.Descriptor instead.
func (*StartSessionRequest) Descriptor() ([]byte, []int) {
	return file_whatsapp_proto_rawDescGZIP(), []int{0}
}

// Response containing session details
type SessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     int64                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	QrCode        string                 `protobuf:"bytes,2,opt,name=qr_code,json=qrCode,proto3" json:"qr_code,omitempty"`
	Jid           string                 `protobuf:"bytes,3,opt,name=jid,proto3" json:"jid,omitempty"`       // WhatsApp ID of the user
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // Can be "connected", "disconnected", "error"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionResponse) Reset() {
	*x = SessionResponse{}
	mi := &file_whatsapp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionResponse) ProtoMessage() {}

func (x *SessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whatsapp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionResponse.ProtoReflect.Descriptor instead.
func (*SessionResponse) Descriptor() ([]byte, []int) {
	return file_whatsapp_proto_rawDescGZIP(), []int{1}
}

func (x *SessionResponse) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *SessionResponse) GetQrCode() string {
	if x != nil {
		return x.QrCode
	}
	return ""
}

func (x *SessionResponse) GetJid() string {
	if x != nil {
		return x.Jid
	}
	return ""
}

func (x *SessionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Request to check session status
type SessionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jid           string                 `protobuf:"bytes,1,opt,name=jid,proto3" json:"jid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStatusRequest) Reset() {
	*x = SessionStatusRequest{}
	mi := &file_whatsapp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStatusRequest) ProtoMessage() {}

func (x *SessionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whatsapp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStatusRequest.ProtoReflect.Descriptor instead.
func (*SessionStatusRequest) Descriptor() ([]byte, []int) {
	return file_whatsapp_proto_rawDescGZIP(), []int{2}
}

func (x *SessionStatusRequest) GetJid() string {
	if x != nil {
		return x.Jid
	}
	return ""
}

// Response with session status
type SessionStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsConnected   bool                   `protobuf:"varint,1,opt,name=is_connected,json=isConnected,proto3" json:"is_connected,omitempty"`
	QrCode        string                 `protobuf:"bytes,2,opt,name=qr_code,json=qrCode,proto3" json:"qr_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStatusResponse) Reset() {
	*x = SessionStatusResponse{}
	mi := &file_whatsapp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStatusResponse) ProtoMessage() {}

func (x *SessionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whatsapp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStatusResponse.ProtoReflect.Descriptor instead.
func (*SessionStatusResponse) Descriptor() ([]byte, []int) {
	return file_whatsapp_proto_rawDescGZIP(), []int{3}
}

func (x *SessionStatusResponse) GetIsConnected() bool {
	if x != nil {
		return x.IsConnected
	}
	return false
}

func (x *SessionStatusResponse) GetQrCode() string {
	if x != nil {
		return x.QrCode
	}
	return ""
}

// Request for sending a message
type SendMessageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SenderJid      string                 `protobuf:"bytes,1,opt,name=sender_jid,json=senderJid,proto3" json:"sender_jid,omitempty"`
	ToPhoneNumber  string                 `protobuf:"bytes,2,opt,name=to_phone_number,json=toPhoneNumber,proto3" json:"to_phone_number,omitempty"`
	MessageContent string                 `protobuf:"bytes,3,opt,name=message_content,json=messageContent,proto3" json:"message_content,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_whatsapp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whatsapp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_whatsapp_proto_rawDescGZIP(), []int{4}
}

func (x *SendMessageRequest) GetSenderJid() string {
	if x != nil {
		return x.SenderJid
	}
	return ""
}

func (x *SendMessageRequest) GetToPhoneNumber() string {
	if x != nil {
		return x.ToPhoneNumber
	}
	return ""
}

func (x *SendMessageRequest) GetMessageContent() string {
	if x != nil {
		return x.MessageContent
	}
	return ""
}

// Response with message status
type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // Can be "sent", "delivered", "read", "failed"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_whatsapp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whatsapp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_whatsapp_proto_rawDescGZIP(), []int{5}
}

func (x *SendMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendMessageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendMessageResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_whatsapp_proto protoreflect.FileDescriptor

const file_whatsapp_proto_rawDesc = "" +
	"\n" +
	"\x0ewhatsapp.proto\x12\bwhatsapp\"\x15\n" +
	"\x13StartSessionRequest\"s\n" +
	"\x0fSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x03R\tsessionId\x12\x17\n" +
	"\aqr_code\x18\x02 \x01(\tR\x06qrCode\x12\x10\n" +
	"\x03jid\x18\x03 \x01(\tR\x03jid\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"(\n" +
	"\x14SessionStatusRequest\x12\x10\n" +
	"\x03jid\x18\x01 \x01(\tR\x03jid\"S\n" +
	"\x15SessionStatusResponse\x12!\n" +
	"\fis_connected\x18\x01 \x01(\bR\visConnected\x12\x17\n" +
	"\aqr_code\x18\x02 \x01(\tR\x06qrCode\"\x84\x01\n" +
	"\x12SendMessageRequest\x12\x1d\n" +
	"\n" +
	"sender_jid\x18\x01 \x01(\tR\tsenderJid\x12&\n" +
	"\x0fto_phone_number\x18\x02 \x01(\tR\rtoPhoneNumber\x12'\n" +
	"\x0fmessage_content\x18\x03 \x01(\tR\x0emessageContent\"f\n" +
	"\x13SendMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status2\x86\x02\n" +
	"\x0fWhatsAppService\x12L\n" +
	"\fStartSession\x12\x1d.whatsapp.StartSessionRequest\x1a\x19.whatsapp.SessionResponse\"\x000\x01\x12W\n" +
	"\x12CheckSessionStatus\x12\x1e.whatsapp.SessionStatusRequest\x1a\x1f.whatsapp.SessionStatusResponse\"\x00\x12L\n" +
	"\vSendMessage\x12\x1c.whatsapp.SendMessageRequest\x1a\x1d.whatsapp.SendMessageResponse\"\x00B\x03Z\x01/b\x06proto3"

var (
	file_whatsapp_proto_rawDescOnce sync.Once
	file_whatsapp_proto_rawDescData []byte
)

func file_whatsapp_proto_rawDescGZIP() []byte {
	file_whatsapp_proto_rawDescOnce.Do(func() {
		file_whatsapp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_whatsapp_proto_rawDesc), len(file_whatsapp_proto_rawDesc)))
	})
	return file_whatsapp_proto_rawDescData
}

var file_whatsapp_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_whatsapp_proto_goTypes = []any{
	(*StartSessionRequest)(nil),   // 0: whatsapp.StartSessionRequest
	(*SessionResponse)(nil),       // 1: whatsapp.SessionResponse
	(*SessionStatusRequest)(nil),  // 2: whatsapp.SessionStatusRequest
	(*SessionStatusResponse)(nil), // 3: whatsapp.SessionStatusResponse
	(*SendMessageRequest)(nil),    // 4: whatsapp.SendMessageRequest
	(*SendMessageResponse)(nil),   // 5: whatsapp.SendMessageResponse
}
var file_whatsapp_proto_depIdxs = []int32{
	0, // 0: whatsapp.WhatsAppService.StartSession:input_type -> whatsapp.StartSessionRequest
	2, // 1: whatsapp.WhatsAppService.CheckSessionStatus:input_type -> whatsapp.SessionStatusRequest
	4, // 2: whatsapp.WhatsAppService.SendMessage:input_type -> whatsapp.SendMessageRequest
	1, // 3: whatsapp.WhatsAppService.StartSession:output_type -> whatsapp.SessionResponse
	3, // 4: whatsapp.WhatsAppService.CheckSessionStatus:output_type -> whatsapp.SessionStatusResponse
	5, // 5: whatsapp.WhatsAppService.SendMessage:output_type -> whatsapp.SendMessageResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_whatsapp_proto_init() }
func file_whatsapp_proto_init() {
	if File_whatsapp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_whatsapp_proto_rawDesc), len(file_whatsapp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_whatsapp_proto_goTypes,
		DependencyIndexes: file_whatsapp_proto_depIdxs,
		MessageInfos:      file_whatsapp_proto_msgTypes,
	}.Build()
	File_whatsapp_proto = out.File
	file_whatsapp_proto_goTypes = nil
	file_whatsapp_proto_depIdxs = nil
}
